---
name: Pulumi
on:
  push:
    branches:
      - main
    paths-ignore:
      - README*
  pull_request:
jobs:
  up:
    name: Up we go
    runs-on: ubuntu-latest
    env:
      # Azure credentials
      ARM_USE_MSI: true
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      # Access token to Pulumi state
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      # Values needed for web app
      DB_URI: ${{ secrets.DB_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      # Values needed for DB
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner, and setup node
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
